export const PRODUCTS_MICROSERVICE_NAME = 'PRODUCTS_MICROSERVICE';

export const PRODUCTS_MICROSERVICE_MESSAGE_CREATE_PRODUCT = 'create_product';
export const PRODUCTS_MICROSERVICE_MESSAGE_FIND_ONE = 'find_one_product';
export const PRODUCTS_MICROSERVICE_MESSAGE_UPDATE_PRODUCT = 'update_product';
export const PRODUCTS_MICROSERVICE_MESSAGE_DELETE_PRODUCT = 'delete_product';
export const PRODUCTS_MICROSERVICE_MESSAGE_FIND_ALL_PRODUCT =
  'find_all_product';
export const PRODUCTS_MICROSERVICE_MESSAGE_VALIDATE_PRODUCT =
  'validate_product';

export const ORDERS_MICROSERVICE_NAME = 'ORDERS_MICROSERVICE';

export const ORDERS_MICROSERVICE_MESSAGE_CREATE_ORDER = 'create_order';
export const ORDERS_MICROSERVICE_MESSAGE_FIND_ONE = 'find_one_order';
export const ORDERS_MICROSERVICE_MESSAGE_CHANGE_ORDER_STATUS =
  'change_order_status';
export const ORDERS_MICROSERVICE_MESSAGE_FIND_ALL_ORDER = 'find_all_order';

export const NATS_SERVICE = 'NATS_SERVICE';
